### ISSUE TITLE
[Suggestion] Using advertools crawler

### ISSUE THREAD

**Issue by eliasdabbas** [brknlpr/seochecks#1]
I saw you are using `advertools` for getting sitemaps. I hope it's working fine!

I just wanted to suggest using the [`crawl`](https://advertools.readthedocs.io/en/master/advertools.spider.html) function, which retrieves all the elements you want in [`sitecheck.py`](https://github.com/brknlpr/seochecks/blob/main/sitecheck.py). 
It also handles crawling rules, retries, large-scale crawling, and more.

Good luck!

**Comment by brknlpr** [comment]
thanks for suggestion, will check it
